import { Code } from "~/components/dotfiles/code";
import { Command } from "~/components/dotfiles/command";
import { CommandContainer } from "~/components/dotfiles/command-container";
import { ExternalLink } from "~/components/dotfiles/external-link";

const Page = () => {
  return (
    <div className="grid grid-flow-row gap-2 mx-auto w-[40%] py-20">
      <p>install guide for alpha dotfiles</p>
      <div className="pt-10">
        <p>Getting started</p>
        <br />
        <p>
          If you want to follow along exactly, first install EndeavourOS with the GNOME DE.
          EndeavourOS will automatically set it up for you.
        </p>
        <br />
        <p>
          Once you have EndeavourOS installed boot into it and press Ctrl+Alt+F2 to launch the tty.
          The first thing to install is Hyprland which is going to be the DE. To install Hyprland
          just run:
        </p>
        <br />
        <CommandContainer>
          <Command command="sudo pacman -S hyprland" />
          <br />
          <Command comment="then run this command to start hyprland" command="Hyprland" />
        </CommandContainer>
        <br />
        <p>
          You will also need to install some programs like kitty (terminal emulator), nemo (file
          manager), and wofi (app launcher) so exit hyprland with SUPER+M and install:
        </p>
        <br />
        <CommandContainer>
          <Command command="sudo pacman -S kitty nemo wofi" />
        </CommandContainer>
        <br />
        <p>You will also need to update your hyprland.conf so it knows to use these programs</p>
        <br />
        <CommandContainer>
          <Command comment="should be autogenerated by hyprland" command="cd ~/.config/hypr" />
          <br />
          <Command comment="install vim if not installed" command="sudo pacman -S vim" />
          <br />
          <Command comment="edit hyprland config" command="vim hyprland.conf" />
        </CommandContainer>
        <br />
        <p>Just change these variables in your hyprland.conf to this</p>
        <br />
        <CommandContainer>
          <Code text={`$terminal = kitty\n$fileManager = nemo\n$menu = wofi --show drun`} />
        </CommandContainer>
        <br />
        <p>
          [!] If you're installing this on a VM, kitty might not work and many other things in this
          guide may not work either, if you still want to try do this in a VM, try foot instead of
          kitty
        </p>
        <br />
        <p>
          You will probably need to configure your monitors, to do that first get the name of your
          monitors
        </p>
        <br />
        <CommandContainer>
          <Command comment="this will output your monitor info" command="hyprctl monitors" />
        </CommandContainer>
        <br />
        <p>
          Then adjust your hyprland.conf accordingly. Here is what it would look like assuming your
          monitor names are DP-1 and DP-2 (it may different for you, see{" "}
          <ExternalLink url="https://wiki.hyprland.org/Configuring/Monitors" />
          ).
        </p>
        <br />
        <CommandContainer>
          <Code
            text={`monitor=DP-1,1920x1080@165,1920x1080,auto
monitor=DP-2,1920x1080@165,0x1080,auto`}
          />
        </CommandContainer>
        <br />
      </div>
    </div>
  );
};

export default Page;
