import { Q } from "~/components/configs/quote";
import { AlphaText } from "~/components/dotfiles/alpha-text";
import { Code } from "~/components/dotfiles/code";
import { Command } from "~/components/dotfiles/command";
import { CommandContainer } from "~/components/dotfiles/command-container";
import { ExternalLink } from "~/components/dotfiles/external-link";
import { Header } from "~/components/dotfiles/header";
import { ProgramSlot } from "~/components/dotfiles/program-slot";
import { Warning } from "~/components/dotfiles/warning";

const Page = () => {
  return (
    <div className="grid grid-flow-row mx-auto w-[95%] lg:w-[60%] xl:w-[40%] py-20">
      <AlphaText />
      <p className="text-center">
        install guide for <span className="text-teal-700">alpha</span> dotfiles
      </p>
      <Header name="info" />
      this setup uses the following programs:
      <br />
      <br />
      <div className="grid grid-flow-row w-max">
        <ProgramSlot purpose="Distro" name="EndeavourOS" url="https://endeavouros.com/" />
        <ProgramSlot purpose="DE/WM/Compositor" name="hyprland" url="https://hyprland.org/" />
        <ProgramSlot
          purpose="Terminal Emulator"
          name="kitty"
          url="https://github.com/kovidgoyal/kitty"
        />
        <ProgramSlot purpose="Shell" name="kitty" url="https://github.com/kovidgoyal/kitty" />
        <ProgramSlot
          purpose="App Launcher"
          name="wofi"
          url="https://man.archlinux.org/man/wofi.1.en"
        />
        <ProgramSlot purpose="Taskbar" name="waybar" url="https://github.com/Alexays/Waybar" />
        <ProgramSlot
          purpose="File Manager"
          name="nemo"
          url="https://wiki.archlinux.org/title/Nemo"
        />
        <ProgramSlot purpose="IDE" name="VSCode" url="https://code.visualstudio.com/" />
      </div>
      <br />
      <Header name="getting-started" />
      <p>
        If you want to follow along exactly, first install EndeavourOS with the GNOME Desktop
        Environment. EndeavourOS will allow you to choose this in the install setup.
      </p>
      <br />
      <Header name="installing-hyprland" />
      <p>
        Once you have EndeavourOS installed boot into it and press <Q>Ctrl+Alt+F2</Q> to launch the
        tty. The first thing to install is Hyprland which is going to be the DE. To install Hyprland
        just run:
      </p>
      <br />
      <CommandContainer>
        <Command command="sudo pacman -S hyprland" />
        <br />
        <Command comment="then run this command to start hyprland" command="Hyprland" />
      </CommandContainer>
      <br />
      <Header name="configuring-hyprland" />
      <p>
        You will also need to install some programs like kitty (terminal emulator), nemo (file
        manager), and wofi (app launcher) so exit hyprland with <Q>SUPER+M</Q> and install:
      </p>
      <br />
      <Warning>
        If you're installing this on a VM, kitty might not work and many other things in this guide
        may not work either, if you still want to try do this in a VM, try `foot` instead of kitty
      </Warning>
      <br />
      <CommandContainer>
        <Command command="sudo pacman -S kitty nemo wofi" />
      </CommandContainer>
      <br />
      <p>
        You will also need to update your <Q>hyprland.conf</Q> so it knows to use these programs
      </p>
      <br />
      <CommandContainer>
        <Command comment="should be autogenerated by hyprland" command="cd ~/.config/hypr" />
        <br />
        <Command comment="install vim if not installed" command="sudo pacman -S vim" />
        <br />
        <Command comment="edit hyprland config" command="vim hyprland.conf" />
      </CommandContainer>
      <br />
      <p>
        Just change these variables in your hyprland.conf to this (<Q>CTRL+SHIFT+V</Q> or
        middle-click to paste)
      </p>
      <br />
      <CommandContainer>
        <Code
          name="hyprland.conf"
          text={`...\n$terminal = kitty\n$fileManager = nemo\n$menu = wofi --show drun\n...`}
        />
      </CommandContainer>
      <br />
      <p>
        You will probably need to configure your monitors, to do that first get the name of your
        monitors
      </p>
      <br />
      <CommandContainer>
        <Command comment="this will output your monitor info" command="hyprctl monitors" />
      </CommandContainer>
      <br />
      <p>
        Then adjust your hyprland.conf accordingly. Here is what it would look like assuming your
        monitor names are DP-1 and DP-2 (it may different for you, it's what you got from running
        hyprctl monitors, see <ExternalLink url="https://wiki.hyprland.org/Configuring/Monitors" />
        ).
      </p>
      <br />
      <CommandContainer>
        <Code
          name="hyprland.conf"
          text={`monitor=DP-1,1920x1080@165,1920x1080,auto
monitor=DP-2,1920x1080@165,0x1080,auto`}
        />
      </CommandContainer>
      <br />
      <p>
        If you have multiple monitors and want to have separate workspaces for each monitor you can
        use a program called hyprsome by sopa0 (
        <ExternalLink url="https://github.com/sopa0/hyprsome" />)
      </p>
      <br />
      <p>For now don't worry about that you can come back to this later</p>
      <br />
      <Header name="setting-wallpaper" />
      <p>
        To set a wallpaper, I used a program called <Q>hyprpaper</Q>, which works well with hyprland
      </p>
      <br />
      <CommandContainer>
        <Command command="sudo pacman -S hyprpaper" />
      </CommandContainer>
      <br />
      <p>
        To set a wallpaper I would suggest creating a hidden folder in like <Q>.wallpapers</Q> in
        your home directory add putting your wallpapers there
      </p>
      <br />
      <p>
        To actually set the wallpaper, edit the <Q>hyprpaper.conf</Q> file
      </p>
      <br />
      <CommandContainer>
        <Command command="cd ~/.config/hypr" />
        <br />
        <Command comment="if hyprpaper.conf doesn't exit" command="touch hyprpaper.conf" />
        <br />
        <Command command="vim hyprpaper.conf" />
      </CommandContainer>
      <br />
      <p>
        set preload to and wallpaper to whatever you named your wallpaper file. you can also choose
        a wallpaper to set for each monitor.
      </p>
      <br />
      <CommandContainer>
        <Code
          name="hyprpaper.conf"
          text={`preload = ~/.wallpapers/wall0.jpg

wallpaper = DP-1,~/.wallpapers/wall0.jpg
wallpaper = DP-2,~/.wallpapers/wall0.jpg
# .. more monitors

# disable messages on bottom
splash = false

# fully disable ipc
# ipc = off`}
        />
      </CommandContainer>
      <br />
      <p>After, just add this line in your hyprland.conf to execute hyprpaper as hyprland starts</p>
      <br />
      <CommandContainer>
        <Code name="hyprland.conf" text="exec-once = hyprpaper" />
      </CommandContainer>
      <br />
      <Header name="configuring-waybar" />
      <p>
        For the taskbar, I used <Q>waybar</Q> which works well with hyprland
      </p>
      <br />
      <CommandContainer>
        <Command command="sudo pacman -S waybar" />
      </CommandContainer>
    </div>
  );
};

export default Page;
